Add SA1Hybridizer
SMWCentral/OnlineTools pull request #1
Opened 2021-07-18 07:53 UTC by Atari2

This is basically a straight up port of sa1hybridizer (https://github.com/Atari2/SA1Hybridizer) to javascript. 
I also fixed a minor typo in the README.

2021-07-27 13:11 UTC, telinc1 requested changes
This port is still too unstable to accept. The code uses (what I assume is) Python syntax that behaves differently in JS and malfunctions as result. For example, I tried it on the [Circling Thwomp](https://smwc.me/s/13893) and it missed a `$7FAB10` that the Python version converted correctly (fwiw, the Python version also modified a `$0020` that should have been left alone, but that's to be expected from an automated tool).

I've pointed out the mistakes that caught my eye, but I've probably missed some. I'm not familiar with Python or with this code, so I don't feel comfortable fixing/testing all of the possible branches myself.

2021-07-27 13:11 UTC, telinc1 commented on src/sa1hybridizer/index.js
> +        return b <= bwram_word <= e;
No such syntax exists in JavaScript and this will always return `true`. It's interpreted as `(b <= bwram_word) <= e`. The left-hand side is a boolean, which when cast to a number, will result in e.g. `0 <= e`.

Don't know Python, but I assume this is what you meant?
```suggestion
        return b <= bwram_word && bwram_word <= e;
```

2021-07-27 13:11 UTC, telinc1 commented on src/sa1hybridizer/index.js
> +        numeric_word = parseInt(word, 16);
`parseInt` doesn't throw errors. For invalid input, it returns `NaN`, which will then spread through the rest of the code (you can detect NaNs with `Number.isNaN`).

2021-07-27 13:11 UTC, telinc1 commented on src/sa1hybridizer/index.js
> +        word, bwram_define_needed = check_bwram(word);
JS interprets this as two separate expressions, `word` (which is essentially a no-op) and `bwram_define_needed = check_bwram(word);`. Since `check_bwram` returns an array, `bwram_define_needed` will always be truthy. I assume you meant to use a destructuring syntax instead.
```suggestion
        [word, bwram_define_needed] = check_bwram(word);
```

2021-07-27 13:11 UTC, telinc1 commented on src/sa1hybridizer/index.js
> +            outlines[index] = line.trimStart();
`trimStart` or `trimEnd`? The Python version uses `rstrip`. This one destroys indentation.

2021-07-27 13:11 UTC, telinc1 commented on src/sa1hybridizer/index.js
> +                                comma_index = word_tuples[i + 1][0] === WordType.COMMA ? i + 1 : -1;
Shouldn't this be `word_tuples[i + 1].type`? That should produce identical behavior to the Python version, though I'm not sure exactly where it expects its `IndexError`s from.

2021-07-27 13:11 UTC, telinc1 commented on src/sa1hybridizer/index.js
> +        let true_index = bwram_indexes.indexOf(True)
`True` is undefined, `true` is a literal boolean.
```suggestion
        let true_index = bwram_indexes.indexOf(true)
```

2021-07-27 15:54 UTC, Atari2 commented on src/sa1hybridizer/index.js
> +        let true_index = bwram_indexes.indexOf(True)
Fixed in 010b017cb417f4e3d9f01b938abf4a2a9697f87c

2021-07-27 15:55 UTC, Atari2 commented on src/sa1hybridizer/index.js
> +                                comma_index = word_tuples[i + 1][0] === WordType.COMMA ? i + 1 : -1;
This is fixed now, the IndexError could happen when index in word_tuples with i + 1, however js doesn't throw when accessing out of bounds so I restructured this part.

2021-07-27 15:55 UTC, Atari2 commented on src/sa1hybridizer/index.js
> +            outlines[index] = line.trimStart();
Fixed in 010b017cb417f4e3d9f01b938abf4a2a9697f87c

2021-07-27 15:55 UTC, Atari2 commented on src/sa1hybridizer/index.js
> +        word, bwram_define_needed = check_bwram(word);
Fixed in 010b017cb417f4e3d9f01b938abf4a2a9697f87c

2021-07-27 15:56 UTC, Atari2 commented on src/sa1hybridizer/index.js
> +        numeric_word = parseInt(word, 16);
Done (and also fixed in another place that did the same thing)

2021-07-27 15:56 UTC, Atari2 commented on src/sa1hybridizer/index.js
> +        return b <= bwram_word <= e;
Fixed in 010b017cb417f4e3d9f01b938abf4a2a9697f87c

2021-07-28 12:51 UTC, telinc1 approved these changes
Looks good now. Thanks for your contribution!

2021-07-28 12:52 UTC, merged